# Generated by Django 4.1 on 2023-04-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_active_userprofile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=50)),
                ('from_year', models.CharField(max_length=50)),
                ('to_year', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('specialization', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('institution', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=50)),
                ('from_year', models.CharField(max_length=50)),
                ('to_year', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('coins', models.FloatField(default=0)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('work_experience', models.CharField(max_length=50)),
                ('education', models.ManyToManyField(to='accounts.education')),
                ('skill', models.ManyToManyField(to='accounts.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_history', models.ManyToManyField(to='accounts.work_experience')),
            ],
        ),
    ]
