# Generated by Django 4.1 on 2023-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_education_skill_work_experience_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_history',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.work_experience'),
        ),
    ]
