# Generated by Django 4.1 on 2023-03-20 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Self Paced Courses', 'Self Paced Courses'), ('Live Coherts', 'Live Coherts')], default='Self Paced Courses', max_length=20),
        ),
    ]
