# Generated by Django 4.1 on 2023-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_date_created_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='career_grouth_prospect',
            new_name='career_growth_prospect',
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Self Paced Courses', 'Self Paced Courses'), ('Live Coherts', 'Live Coherts')], max_length=20),
        ),
    ]
