# Generated by Django 4.1 on 2023-03-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_career_grouth_prospect_course_career_growth_prospect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.instructor'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ManyToManyField(to='courses.instructor'),
        ),
    ]
