# Generated by Django 4.1 on 2023-03-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_content_instructor_section_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='course_cover/'),
        ),
    ]
