# Generated by Django 4.1 on 2023-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_profile/'),
        ),
    ]
