# Generated by Django 3.2.18 on 2023-04-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('headline', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True)),
                ('expertise', models.CharField(max_length=500)),
                ('mentoring_style', models.TextField(blank=True)),
                ('language', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=150)),
                ('work_experience', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('section', models.CharField(max_length=250)),
                ('mentor', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='mentorcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mentor', models.ManyToManyField(to='mentorships.Mentor')),
                ('mentor_content', models.ManyToManyField(related_name='mentorcontent', to='mentorships.MentorContent')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorships.mentor')),
            ],
        ),
    ]
