# Generated by Django 3.2.18 on 2023-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_type',
            field=models.CharField(choices=[('technology', 'Technology'), ('management', 'Management')], max_length=100, null=True),
        ),
    ]
