# Generated by Django 4.1 on 2023-05-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0002_mentor_mentor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='language',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mentor_type',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mentoring_style',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='work_experience',
        ),
    ]
